-- liquibase formatted sql

-- changeset oojuniin:roles-v1-initial context:structure labels:api,roles
-- comment: Cria a tabela inicial para registrar as permissões (roles)
-- preconditions onFail:MARK_RAN onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'api' AND table_name = 'roles'
create table api.roles
(
    id         BIGINT generated by default as identity,
    authority  varchar(255) not null,
    created_at timestamp(6),
    created_by varchar(255),
    updated_at timestamp(6),
    updated_by varchar(255),

    primary key (id)
);

-- changeset oojuniin:users_api-v1-initial context:structure labels:api,users_api
-- comment: Cria a tabela inicial para registrar os usuarios da api (users_api)
-- preconditions onFail:MARK_RAN onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'api' AND table_name = 'users_api'
create table api.users_api
(
    id                         UUID         not null,
    username                   varchar(50)  not null unique,
    password                   varchar(255) not null,
    is_enabled                 boolean      not null,
    is_account_non_expired     boolean,
    is_account_non_locked      boolean,
    is_credentials_non_expired boolean,
    created_at                 timestamp(6),
    created_by                 varchar(255),
    updated_at                 timestamp(6),
    updated_by                 varchar(255),

    primary key (id)
);

-- changeset oojuniin:user_roles-v1-initial context:structure labels:api,user_roles
-- comment: Cria a tabela inicial para registrar as roles dos usuarios (user_roles)
-- preconditions onFail:MARK_RAN onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'api' AND table_name = 'user_roles'
create table api.user_roles
(
    user_id UUID   NOT NULL,
    role_id BIGINT NOT NULL,

    primary key (role_id, user_id)
)