-- liquibase formatted sql

-- changeset junior.lima:create_table_roles-00 context:structure
-- comment create table roles
-- preconditions onFail:MARK_RAN onError:HALT
-- precondition-sql-check expectedResult:0 SELECT count(*) FROM pg_catalog.pg_tables pt WHERE UPPER(pt.TABLENAME) = UPPER('roles');
-- Author: Junior Lima
-- Date: 2024-11-23
-- Description: Cria a tabela roles
create table api.roles (
   id bigint generated by default as identity,
   authority varchar(255) not null,
   created_at timestamp(6),
   created_by varchar(255),
   updated_at timestamp(6),
   updated_by varchar(255),

   primary key (id)
)