create table roles (
   id bigint generated by default as identity,
   authority varchar(255) not null,
   created_at timestamp(6),
   created_by varchar(255),
   updated_at timestamp(6),
   updated_by varchar(255),

   primary key (id)
)