spring.main.banner-mode=console
spring.output.ansi.enabled=always

spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.default-schema=${SCHEMA:workbox}

spring.jpa.properties.hibernate.default_schema=${SCHEMA}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.format_sql=false
spring.jpa.properties.show_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=false

debug=false
logging.pattern.console=%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n
logging.level.org.springframework.jdbc.datasource.init=error
logging.level.org.springframework.boot.autoconfigure=error
logging.level.net.lbruun.springboot.preliquibase=error
logging.level.liquibase=error
logging.level.root=info
logging.level.web=info


