spring.main.banner-mode=console
spring.output.ansi.enabled=always

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/workbox}
spring.datasource.username=${POSTGRES_USER:workbox_api}
spring.datasource.password=${POSTGRES_PASSWORD:workbox_api}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.default-schema=${SCHEMA:api}
spring.liquibase.liquibase-schema=${SCHEMA_LIQUIBASE:api_liquibase}

spring.jpa.properties.hibernate.default_schema=${SCHEMA:api}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.format_sql=true
spring.jpa.properties.show_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true

debug=false
logging.level.web=info
logging.level.root=info
logging.level.liquibase=info
logging.level.org.springframework.security=info
logging.level.net.lbruun.springboot.preliquibase=info
logging.level.org.springframework.boot.autoconfigure=info
logging.level.org.springframework.jdbc.datasource.init=info
#logging.pattern.console=%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){blue} %clr(%-5p) %clr([env:${spring.profiles.active}]){green} %clr(${PID}){faint} %clr([%thread]){cyan} %clr(%logger{36}){yellow} %clr(:){red} %clr(%m){faint}%n

server.error.include-path=always
server.error.include-message=always
server.error.include-exception=true
server.error.include-stacktrace=always
server.error.include-binding-errors=always

