spring.application.name=api
spring.profiles.active=${PROFILE_ACTIVE:dev}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog.yaml
spring.jpa.open-in-view=false
server.port=${PORT:8080}
server.servlet.context-path=/api
jwt.secret=${JWT_SECRET:MyS3cur3P@ssw0rd12345!ThisIs32Bytes!}
admin.password=admin
