-- liquibase formatted sql

-- changeset oojuniin:modules-v1-initial context:structure labels:api,modules
-- comment: Catalogo de modulos do sistema (Financas, Forza...). Catalogo fechado: modulo novo entra sempre por changeset novo, junto com a role que libera o acesso a ele (ver roles.module_id). Nao ha CRUD na API.
-- preconditions onFail:MARK_RAN onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'workbox' AND table_name = 'modules'
CREATE TABLE workbox.modules
(
    id   BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50)  NOT NULL,
    name VARCHAR(120) NOT NULL,
    CONSTRAINT uk_modules_code UNIQUE (code)
);

-- changeset oojuniin:modules-v1-seed-financas-forza context:data labels:api,modules
-- comment: Modulos ja liberados no front (notes-service ainda nao e consumido pelo app, entra com o proprio modulo).
-- preconditions onFail:MARK_RAN onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM workbox.modules WHERE code IN ('FINANCAS', 'FORZA')
INSERT INTO workbox.modules (code, name)
VALUES ('FINANCAS', 'Finanças'),
       ('FORZA', 'Forza');
-- rollback DELETE FROM workbox.modules WHERE code IN ('FINANCAS', 'FORZA');
